
<?php $msg;?>
<form class="form" action="/magento2/survey/index/result" method="post">
<!--in the form tag action property url could be differ because i'm testing in the xampp, uniserver and virtual server but
every magento installation basic url was different so it can be defined depends on the basic magento url-->

<fieldset class="fieldset">
    <legend class="legend"><span>Survey</span></legend><br>
    <div class="field required">
        <label for="question1" class="label">
            Was our service satisfied?
        </label>

        <div class="control">
            <input type="text" id="question1"
                   name="question1"
                   class="input-text">
        </div>
    </div>
    <div class="field required">
        <label for="question2" class="label">
            Did you have problem with finding product?
        </label>

        <div class="control">
            <input type="text" id="question2"
                   name="question2"
                   class="input-text">
        </div>
    </div>
    <div class="field required">
        <label for="question3" class="label">
            Is there anything that we can make it better among our services?
        </label>

        <div class="control">
            <input type="text" id="question3"
                   name="question3"
                   class="input-text">
        </div>
    </div>
    <div class="field required">
        <label for="product" class="label">
            What product was that looking for?
        </label>

        <div class="control">
            <input type="text" id="product"
                   name="product"
                   class="input-text">
        </div>
    </div>
    
</fieldset>

<div class="actions-toolbar">
    <div class="primary">
        <button type="submit" class="action submit primary" title="Submit">
            <span>Submit</span>
        </button>
    </div>
</div>

</form>

