

<form class="form" action="/survey/index/result" method="post">

<fieldset class="fieldset">
    <legend class="legend"><span>Survey</span></legend><br>
    <div class="field required">
        <label for="question1" class="label">
            Question1
        </label>

        <div class="control">
            <input type="text" id="question1"
                   name="question1"
                   class="input-text">
        </div>
    </div>
    <div class="field required">
        <label for="question1" class="label">
            Question2
        </label>

        <div class="control">
            <input type="text" id="question2"
                   name="question2"
                   class="input-text">
        </div>
    </div>
</fieldset>

<div class="actions-toolbar">
    <div class="primary">
        <button type="submit" class="action submit primary" title="Submit">
            <span>Submit</span>
        </button>
    </div>
</div>

</form>
